"""Added Profile Picture

Revision ID: 7cb5dbd3d54b
Revises: 4d4ffccd5952
Create Date: 2022-09-14 16:19:23.668451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb5dbd3d54b'
down_revision = '4d4ffccd5952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pfp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pfp')
    # ### end Alembic commands ###
