"""Tweaked Likes

Revision ID: a8f487c07825
Revises: 79e8349c810f
Create Date: 2022-09-14 22:24:27.293560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8f487c07825'
down_revision = '79e8349c810f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_ibfk_2', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['poster_id'], ['id'])
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_ibfk_2', 'likes', 'users', ['user_id'], ['id'])
    op.drop_column('likes', 'poster_id')
    # ### end Alembic commands ###
