"""Removed About

Revision ID: aa4974c0133f
Revises: b843f226c912
Create Date: 2022-09-14 13:54:08.026238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa4974c0133f'
down_revision = 'b843f226c912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
