"""Foreign Key

Revision ID: adab7b9d96e7
Revises: 25b9fcadffec
Create Date: 2022-09-14 09:53:18.716618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adab7b9d96e7'
down_revision = '25b9fcadffec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_post', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_post'], ['id'])
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_post')
    # ### end Alembic commands ###
