"""update db

Revision ID: efd6b3ce9ea7
Revises: 25f6c2f670f3
Create Date: 2022-09-16 01:33:41.314970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efd6b3ce9ea7'
down_revision = '25f6c2f670f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commentor', sa.Integer(), nullable=True))
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['commentor'], ['id'])
    op.drop_column('comments', 'commentor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commentor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_1', 'comments', 'users', ['commentor_id'], ['id'])
    op.drop_column('comments', 'commentor')
    # ### end Alembic commands ###
